export default function TermsPage() {
  return (
    <main className="mx-auto flex w-full max-w-2xl flex-col gap-4 px-6 py-16 text-black dark:text-zinc-50">
      <h1 className="text-2xl font-semibold">Terms of Service</h1>
      <p className="text-sm text-zinc-500">Last updated: August 2026</p>

      <p>
        EverySingleVersion is a free, non-commercial service for discovering
        publicly available versions of songs on YouTube. By using this
        site, you agree to the following terms.
      </p>

      <h2 className="text-xl font-medium mt-4">Service description</h2>
      <p>
        The site searches YouTube on your behalf and presents matching
        videos as an embedded playlist. All playback happens on YouTube
        via embedded players; we do not host, download, or redistribute
        any video or audio content.
      </p>

      <h2 className="text-xl font-medium mt-4">No accounts, no warranty</h2>
      <p>
        The service is provided as-is, with no user accounts and no
        guarantee of uptime, accuracy, or completeness of search results.
        Results are generated by an automated heuristic and may include
        mismatches.
      </p>

      <h2 className="text-xl font-medium mt-4">Flagging misuse</h2>
      <p>
        Please use the flag feature only to report genuinely incorrect
        results. Abuse of the flagging feature is rate-limited and may
        result in your flags being ignored.
      </p>

      <h2 className="text-xl font-medium mt-4">YouTube API Services</h2>
      <p>
        This site uses YouTube API Services. By using this site, you also
        agree to be bound by the{" "}
        <a
          href="https://www.youtube.com/t/terms"
          className="underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          YouTube Terms of Service
        </a>{" "}
        and acknowledge{" "}
        <a
          href="https://policies.google.com/privacy"
          className="underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Google&apos;s Privacy Policy
        </a>
        .
      </p>

      <h2 className="text-xl font-medium mt-4">Contact</h2>
      <p>Questions: everysingleversion@gmail.com</p>
    </main>
  );
}
