// Billboard Year-End Hot 100 #1 single for each year, 1950–2025.
// Source: Wikipedia's "Billboard Year-End number-one singles and albums"
// (verified against the live page, not from memory, since this feeds
// real public data). Multi-credit/"featuring" billings are trimmed to
// the primary artist for searchability; genuine duo/group names and
// joint billings (Simon & Garfunkel, Lady Gaga and Bruno Mars) are kept
// as officially credited.
export interface SeedSong {
  year: number;
  song: string;
  artist: string;
}

export const SEED_SONGS: SeedSong[] = [
  { year: 1950, song: "Goodnight, Irene", artist: "The Weavers" },
  { year: 1951, song: "Too Young", artist: "Nat King Cole" },
  { year: 1952, song: "Blue Tango", artist: "Leroy Anderson" },
  { year: 1953, song: "Song from Moulin Rouge", artist: "Percy Faith" },
  { year: 1954, song: "Little Things Mean a Lot", artist: "Kitty Kallen" },
  { year: 1955, song: "Cherry Pink and Apple Blossom White", artist: "Perez Prado" },
  { year: 1956, song: "Heartbreak Hotel", artist: "Elvis Presley" },
  { year: 1957, song: "All Shook Up", artist: "Elvis Presley" },
  { year: 1958, song: "Nel Blu Dipinto di Blu (Volare)", artist: "Domenico Modugno" },
  { year: 1959, song: "The Battle of New Orleans", artist: "Johnny Horton" },
  { year: 1960, song: "Theme from A Summer Place", artist: "Percy Faith" },
  { year: 1961, song: "Tossin' and Turnin'", artist: "Bobby Lewis" },
  { year: 1962, song: "Stranger on the Shore", artist: "Mr. Acker Bilk" },
  { year: 1963, song: "Sugar Shack", artist: "Jimmy Gilmer and the Fireballs" },
  { year: 1964, song: "I Want to Hold Your Hand", artist: "The Beatles" },
  { year: 1965, song: "Wooly Bully", artist: "Sam the Sham & the Pharaohs" },
  { year: 1966, song: "The Ballad of the Green Berets", artist: "Barry Sadler" },
  { year: 1967, song: "To Sir with Love", artist: "Lulu" },
  { year: 1968, song: "Hey Jude", artist: "The Beatles" },
  { year: 1969, song: "Sugar, Sugar", artist: "The Archies" },
  { year: 1970, song: "Bridge over Troubled Water", artist: "Simon & Garfunkel" },
  { year: 1971, song: "Joy to the World", artist: "Three Dog Night" },
  { year: 1972, song: "The First Time Ever I Saw Your Face", artist: "Roberta Flack" },
  { year: 1973, song: "Tie a Yellow Ribbon 'Round the Ole Oak Tree", artist: "Tony Orlando and Dawn" },
  { year: 1974, song: "The Way We Were", artist: "Barbra Streisand" },
  { year: 1975, song: "Love Will Keep Us Together", artist: "Captain & Tennille" },
  { year: 1976, song: "Silly Love Songs", artist: "Wings" },
  { year: 1977, song: "Tonight's the Night (Gonna Be Alright)", artist: "Rod Stewart" },
  { year: 1978, song: "Shadow Dancing", artist: "Andy Gibb" },
  { year: 1979, song: "My Sharona", artist: "The Knack" },
  { year: 1980, song: "Call Me", artist: "Blondie" },
  { year: 1981, song: "Bette Davis Eyes", artist: "Kim Carnes" },
  { year: 1982, song: "Physical", artist: "Olivia Newton-John" },
  { year: 1983, song: "Every Breath You Take", artist: "The Police" },
  { year: 1984, song: "When Doves Cry", artist: "Prince" },
  { year: 1985, song: "Careless Whisper", artist: "Wham!" },
  { year: 1986, song: "That's What Friends Are For", artist: "Dionne Warwick" },
  { year: 1987, song: "Walk Like an Egyptian", artist: "The Bangles" },
  { year: 1988, song: "Faith", artist: "George Michael" },
  { year: 1989, song: "Look Away", artist: "Chicago" },
  { year: 1990, song: "Hold On", artist: "Wilson Phillips" },
  { year: 1991, song: "(Everything I Do) I Do It for You", artist: "Bryan Adams" },
  { year: 1992, song: "End of the Road", artist: "Boyz II Men" },
  { year: 1993, song: "I Will Always Love You", artist: "Whitney Houston" },
  { year: 1994, song: "The Sign", artist: "Ace of Base" },
  { year: 1995, song: "Gangsta's Paradise", artist: "Coolio" },
  { year: 1996, song: "Macarena (Bayside Boys Mix)", artist: "Los del Río" },
  { year: 1997, song: "Candle in the Wind 1997", artist: "Elton John" },
  { year: 1998, song: "Too Close", artist: "Next" },
  { year: 1999, song: "Believe", artist: "Cher" },
  { year: 2000, song: "Breathe", artist: "Faith Hill" },
  { year: 2001, song: "Hanging by a Moment", artist: "Lifehouse" },
  { year: 2002, song: "How You Remind Me", artist: "Nickelback" },
  { year: 2003, song: "In Da Club", artist: "50 Cent" },
  { year: 2004, song: "Yeah!", artist: "Usher" },
  { year: 2005, song: "We Belong Together", artist: "Mariah Carey" },
  { year: 2006, song: "Bad Day", artist: "Daniel Powter" },
  { year: 2007, song: "Irreplaceable", artist: "Beyoncé" },
  { year: 2008, song: "Low", artist: "Flo Rida" },
  { year: 2009, song: "Boom Boom Pow", artist: "The Black Eyed Peas" },
  { year: 2010, song: "Tik Tok", artist: "Kesha" },
  { year: 2011, song: "Rolling in the Deep", artist: "Adele" },
  { year: 2012, song: "Somebody That I Used to Know", artist: "Gotye" },
  { year: 2013, song: "Thrift Shop", artist: "Macklemore & Ryan Lewis" },
  { year: 2014, song: "Happy", artist: "Pharrell Williams" },
  { year: 2015, song: "Uptown Funk", artist: "Mark Ronson" },
  { year: 2016, song: "Love Yourself", artist: "Justin Bieber" },
  { year: 2017, song: "Shape of You", artist: "Ed Sheeran" },
  { year: 2018, song: "God's Plan", artist: "Drake" },
  { year: 2019, song: "Old Town Road", artist: "Lil Nas X" },
  { year: 2020, song: "Blinding Lights", artist: "The Weeknd" },
  { year: 2021, song: "Levitating", artist: "Dua Lipa" },
  { year: 2022, song: "Heat Waves", artist: "Glass Animals" },
  { year: 2023, song: "Last Night", artist: "Morgan Wallen" },
  { year: 2024, song: "Lose Control", artist: "Teddy Swims" },
  { year: 2025, song: "Die with a Smile", artist: "Lady Gaga and Bruno Mars" },
];
