// A deeper pass beyond Billboard's single #1-per-year: well-known,
// broadly popular songs since 1970 across rock, pop, hip-hop, R&B,
// country, electronic, punk, metal, and indie — not chart-verified like
// seed-song-list.ts, just songs unambiguous and famous enough to be
// confident about the canonical title/artist pairing. Some overlap with
// seed-song-list.ts is fine: seed.mts's alreadySeeded() check skips
// duplicates for free.
export interface SeedSong {
  year: number;
  song: string;
  artist: string;
}

export const SEED_SONGS_2: SeedSong[] = [
  // 1970s
  { year: 1970, song: "Fire and Rain", artist: "James Taylor" },
  { year: 1971, song: "What's Going On", artist: "Marvin Gaye" },
  { year: 1971, song: "Maggie May", artist: "Rod Stewart" },
  { year: 1972, song: "Rocket Man", artist: "Elton John" },
  { year: 1972, song: "Superstition", artist: "Stevie Wonder" },
  { year: 1973, song: "Dueling Banjos", artist: "Eric Weissberg" },
  { year: 1973, song: "Money", artist: "Pink Floyd" },
  { year: 1974, song: "Band on the Run", artist: "Paul McCartney and Wings" },
  { year: 1974, song: "Rebel Rebel", artist: "David Bowie" },
  { year: 1975, song: "Bohemian Rhapsody", artist: "Queen" },
  { year: 1975, song: "Born to Run", artist: "Bruce Springsteen" },
  { year: 1976, song: "Hotel California", artist: "Eagles" },
  { year: 1976, song: "Dancing Queen", artist: "ABBA" },
  { year: 1977, song: "Stayin' Alive", artist: "Bee Gees" },
  { year: 1977, song: "Heroes", artist: "David Bowie" },
  { year: 1978, song: "I Will Survive", artist: "Gloria Gaynor" },
  { year: 1978, song: "Le Freak", artist: "Chic" },
  { year: 1979, song: "Another Brick in the Wall", artist: "Pink Floyd" },
  { year: 1979, song: "London Calling", artist: "The Clash" },
  { year: 1979, song: "Rapper's Delight", artist: "The Sugarhill Gang" },
  // 1980s
  { year: 1980, song: "Another One Bites the Dust", artist: "Queen" },
  { year: 1980, song: "Funkytown", artist: "Lipps Inc" },
  { year: 1981, song: "Tainted Love", artist: "Soft Cell" },
  { year: 1981, song: "Rapture", artist: "Blondie" },
  { year: 1982, song: "Billie Jean", artist: "Michael Jackson" },
  { year: 1982, song: "Don't You Want Me", artist: "The Human League" },
  { year: 1983, song: "Sweet Dreams (Are Made of This)", artist: "Eurythmics" },
  { year: 1983, song: "Beat It", artist: "Michael Jackson" },
  { year: 1984, song: "Like a Virgin", artist: "Madonna" },
  { year: 1984, song: "Purple Rain", artist: "Prince" },
  { year: 1984, song: "Girls Just Want to Have Fun", artist: "Cyndi Lauper" },
  { year: 1985, song: "Take On Me", artist: "a-ha" },
  { year: 1985, song: "Money for Nothing", artist: "Dire Straits" },
  { year: 1986, song: "Livin' on a Prayer", artist: "Bon Jovi" },
  { year: 1986, song: "Papa Don't Preach", artist: "Madonna" },
  { year: 1987, song: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { year: 1987, song: "With or Without You", artist: "U2" },
  { year: 1988, song: "Never Gonna Give You Up", artist: "Rick Astley" },
  { year: 1988, song: "Sign o' the Times", artist: "Prince" },
  { year: 1989, song: "Straight Up", artist: "Paula Abdul" },
  { year: 1989, song: "Fight the Power", artist: "Public Enemy" },
  // 1990s
  { year: 1990, song: "Nothing Compares 2 U", artist: "Sinead O'Connor" },
  { year: 1990, song: "Vogue", artist: "Madonna" },
  { year: 1991, song: "Smells Like Teen Spirit", artist: "Nirvana" },
  { year: 1991, song: "Losing My Religion", artist: "R.E.M." },
  { year: 1992, song: "Baby Got Back", artist: "Sir Mix-a-Lot" },
  { year: 1992, song: "Under the Bridge", artist: "Red Hot Chili Peppers" },
  { year: 1993, song: "Creep", artist: "Radiohead" },
  { year: 1993, song: "What's Up", artist: "4 Non Blondes" },
  { year: 1994, song: "Loser", artist: "Beck" },
  { year: 1994, song: "All Apologies", artist: "Nirvana" },
  { year: 1995, song: "Waterfalls", artist: "TLC" },
  { year: 1995, song: "Wonderwall", artist: "Oasis" },
  { year: 1996, song: "Ironic", artist: "Alanis Morissette" },
  { year: 1996, song: "California Love", artist: "2Pac" },
  { year: 1997, song: "Bitter Sweet Symphony", artist: "The Verve" },
  { year: 1997, song: "MMMBop", artist: "Hanson" },
  { year: 1998, song: "My Heart Will Go On", artist: "Celine Dion" },
  { year: 1998, song: "Torn", artist: "Natalie Imbruglia" },
  { year: 1999, song: "Livin' la Vida Loca", artist: "Ricky Martin" },
  { year: 1999, song: "...Baby One More Time", artist: "Britney Spears" },
  // 2000s
  { year: 2000, song: "Oops!... I Did It Again", artist: "Britney Spears" },
  { year: 2000, song: "Beautiful Day", artist: "U2" },
  { year: 2001, song: "Fallin'", artist: "Alicia Keys" },
  { year: 2001, song: "Get Ur Freak On", artist: "Missy Elliott" },
  { year: 2002, song: "Complicated", artist: "Avril Lavigne" },
  { year: 2002, song: "Hey Ya!", artist: "OutKast" },
  { year: 2003, song: "Crazy in Love", artist: "Beyonce" },
  { year: 2003, song: "Seven Nation Army", artist: "The White Stripes" },
  { year: 2004, song: "Toxic", artist: "Britney Spears" },
  { year: 2004, song: "Mr. Brightside", artist: "The Killers" },
  { year: 2005, song: "Since U Been Gone", artist: "Kelly Clarkson" },
  { year: 2005, song: "Gold Digger", artist: "Kanye West" },
  { year: 2006, song: "Crazy", artist: "Gnarls Barkley" },
  { year: 2006, song: "SexyBack", artist: "Justin Timberlake" },
  { year: 2007, song: "Umbrella", artist: "Rihanna" },
  { year: 2007, song: "Rehab", artist: "Amy Winehouse" },
  { year: 2008, song: "Poker Face", artist: "Lady Gaga" },
  { year: 2008, song: "Viva la Vida", artist: "Coldplay" },
  { year: 2009, song: "I Gotta Feeling", artist: "The Black Eyed Peas" },
  { year: 2009, song: "Empire State of Mind", artist: "Jay-Z" },
  // 2010s
  { year: 2010, song: "Just the Way You Are", artist: "Bruno Mars" },
  { year: 2010, song: "Firework", artist: "Katy Perry" },
  { year: 2011, song: "Party Rock Anthem", artist: "LMFAO" },
  { year: 2011, song: "Someone Like You", artist: "Adele" },
  { year: 2012, song: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { year: 2012, song: "Gangnam Style", artist: "Psy" },
  { year: 2013, song: "Get Lucky", artist: "Daft Punk" },
  { year: 2013, song: "Royals", artist: "Lorde" },
  { year: 2014, song: "Blank Space", artist: "Taylor Swift" },
  { year: 2014, song: "All About That Bass", artist: "Meghan Trainor" },
  { year: 2015, song: "Thinking Out Loud", artist: "Ed Sheeran" },
  { year: 2015, song: "Hello", artist: "Adele" },
  { year: 2016, song: "Formation", artist: "Beyonce" },
  { year: 2016, song: "One Dance", artist: "Drake" },
  { year: 2017, song: "Despacito", artist: "Luis Fonsi" },
  { year: 2017, song: "Humble", artist: "Kendrick Lamar" },
  { year: 2018, song: "Havana", artist: "Camila Cabello" },
  { year: 2018, song: "Thank U, Next", artist: "Ariana Grande" },
  { year: 2019, song: "Bad Guy", artist: "Billie Eilish" },
  { year: 2019, song: "Truth Hurts", artist: "Lizzo" },
  // 2020s
  { year: 2020, song: "Watermelon Sugar", artist: "Harry Styles" },
  { year: 2020, song: "Say So", artist: "Doja Cat" },
  { year: 2021, song: "Good 4 U", artist: "Olivia Rodrigo" },
  { year: 2021, song: "Montero", artist: "Lil Nas X" },
  { year: 2022, song: "As It Was", artist: "Harry Styles" },
  { year: 2022, song: "About Damn Time", artist: "Lizzo" },
  { year: 2023, song: "Flowers", artist: "Miley Cyrus" },
  { year: 2023, song: "Cruel Summer", artist: "Taylor Swift" },
  { year: 2024, song: "Espresso", artist: "Sabrina Carpenter" },
  { year: 2024, song: "Not Like Us", artist: "Kendrick Lamar" },
  { year: 2025, song: "Birds of a Feather", artist: "Billie Eilish" },

  // Rock/metal staples not otherwise covered
  { year: 1971, song: "Stairway to Heaven", artist: "Led Zeppelin" },
  { year: 1975, song: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { year: 1980, song: "Back in Black", artist: "AC/DC" },
  { year: 1981, song: "Ace of Spades", artist: "Motorhead" },
  { year: 1983, song: "Cum on Feel the Noize", artist: "Quiet Riot" },
  { year: 1986, song: "Master of Puppets", artist: "Metallica" },
  { year: 1988, song: "One", artist: "Metallica" },
  { year: 1991, song: "Enter Sandman", artist: "Metallica" },
  { year: 1992, song: "Even Flow", artist: "Pearl Jam" },
  { year: 1994, song: "Zombie", artist: "The Cranberries" },
  { year: 2000, song: "In the End", artist: "Linkin Park" },
  { year: 2003, song: "Numb", artist: "Linkin Park" },
  { year: 2004, song: "Duality", artist: "Slipknot" },
  { year: 2007, song: "Before I Forget", artist: "Slipknot" },

  // Country staples
  { year: 1974, song: "Jolene", artist: "Dolly Parton" },
  { year: 1980, song: "9 to 5", artist: "Dolly Parton" },
  { year: 1992, song: "Achy Breaky Heart", artist: "Billy Ray Cyrus" },
  { year: 1998, song: "Man! I Feel Like a Woman!", artist: "Shania Twain" },
  { year: 2004, song: "Before He Cheats", artist: "Carrie Underwood" },
  { year: 2015, song: "Cruise", artist: "Florida Georgia Line" },
  { year: 2019, song: "Old Town Road (Remix)", artist: "Lil Nas X" },

  // Hip-hop/R&B staples
  { year: 1982, song: "The Message", artist: "Grandmaster Flash" },
  { year: 1986, song: "Walk This Way", artist: "Run-D.M.C." },
  { year: 1988, song: "Fast Car", artist: "Tracy Chapman" },
  { year: 1993, song: "Nuthin' but a G Thang", artist: "Dr. Dre" },
  { year: 1994, song: "Juicy", artist: "The Notorious B.I.G." },
  { year: 1996, song: "No Diggity", artist: "Blackstreet" },
  { year: 1998, song: "Hard Knock Life", artist: "Jay-Z" },
  { year: 2000, song: "The Real Slim Shady", artist: "Eminem" },
  { year: 2002, song: "In da Club", artist: "50 Cent" },
  { year: 2004, song: "Drop It Like It's Hot", artist: "Snoop Dogg" },
  { year: 2010, song: "Not Afraid", artist: "Eminem" },
  { year: 2015, song: "Alright", artist: "Kendrick Lamar" },
  { year: 2018, song: "Sicko Mode", artist: "Travis Scott" },
];
