// Billboard Hot 100 #1s since 2000 — not just the year-end champion,
// every song that hit #1 at some point that year. Not chart-verified
// like seed-song-list.ts, just high-confidence real #1s. Overlap with
// the other two lists is fine, alreadySeeded() skips it for free.
export interface SeedSong {
  year: number;
  song: string;
  artist: string;
}

export const SEED_SONGS_3: SeedSong[] = [
  { year: 2000, song: "Smooth", artist: "Santana" },
  { year: 2000, song: "Maria Maria", artist: "Santana" },
  { year: 2000, song: "Breathe", artist: "Faith Hill" },
  { year: 2000, song: "Say My Name", artist: "Destiny's Child" },
  { year: 2000, song: "I Wanna Know", artist: "Joe" },
  { year: 2000, song: "Bent", artist: "Matchbox Twenty" },
  { year: 2000, song: "Music", artist: "Madonna" },
  { year: 2000, song: "Doesn't Really Matter", artist: "Janet Jackson" },
  { year: 2000, song: "Try Again", artist: "Aaliyah" },
  { year: 2000, song: "Jumpin', Jumpin'", artist: "Destiny's Child" },
  { year: 2000, song: "Incomplete", artist: "Sisqo" },
  { year: 2000, song: "Independent Women", artist: "Destiny's Child" },
  { year: 2001, song: "Stutter", artist: "Joe" },
  { year: 2001, song: "Angel", artist: "Shaggy" },
  { year: 2001, song: "It Wasn't Me", artist: "Shaggy" },
  { year: 2001, song: "Lady Marmalade", artist: "Christina Aguilera" },
  { year: 2001, song: "All for You", artist: "Janet Jackson" },
  { year: 2001, song: "I'm Real", artist: "Jennifer Lopez" },
  { year: 2001, song: "U Remind Me", artist: "Usher" },
  { year: 2001, song: "Fallin'", artist: "Alicia Keys" },
  { year: 2001, song: "Family Affair", artist: "Mary J. Blige" },
  { year: 2001, song: "Ms. Jackson", artist: "OutKast" },
  { year: 2001, song: "How You Remind Me", artist: "Nickelback" },
  { year: 2002, song: "Ain't It Funny", artist: "Jennifer Lopez" },
  { year: 2002, song: "Always on Time", artist: "Ja Rule" },
  { year: 2002, song: "Wherever You Will Go", artist: "The Calling" },
  { year: 2002, song: "Foolish", artist: "Ashanti" },
  { year: 2002, song: "Dilemma", artist: "Nelly" },
  { year: 2002, song: "Hot in Herre", artist: "Nelly" },
  { year: 2002, song: "A Moment Like This", artist: "Kelly Clarkson" },
  { year: 2002, song: "Complicated", artist: "Avril Lavigne" },
  { year: 2002, song: "Lose Yourself", artist: "Eminem" },
  { year: 2002, song: "Work It", artist: "Missy Elliott" },
  { year: 2003, song: "In da Club", artist: "50 Cent" },
  { year: 2003, song: "All I Have", artist: "Jennifer Lopez" },
  { year: 2003, song: "21 Questions", artist: "50 Cent" },
  { year: 2003, song: "Get Busy", artist: "Sean Paul" },
  { year: 2003, song: "Crazy in Love", artist: "Beyonce" },
  { year: 2003, song: "Baby Boy", artist: "Beyonce" },
  { year: 2003, song: "Shake Ya Tailfeather", artist: "Nelly" },
  { year: 2003, song: "Stand Up", artist: "Ludacris" },
  { year: 2003, song: "Baby Boy", artist: "Beyonce" },
  { year: 2004, song: "The Way You Move", artist: "OutKast" },
  { year: 2004, song: "My Boo", artist: "Usher" },
  { year: 2004, song: "Burn", artist: "Usher" },
  { year: 2004, song: "Confessions Part II", artist: "Usher" },
  { year: 2004, song: "Yeah!", artist: "Usher" },
  { year: 2004, song: "Goodies", artist: "Ciara" },
  { year: 2004, song: "Lean Back", artist: "Terror Squad" },
  { year: 2004, song: "Slow Motion", artist: "Juvenile" },
  { year: 2005, song: "Since U Been Gone", artist: "Kelly Clarkson" },
  { year: 2005, song: "Candy Shop", artist: "50 Cent" },
  { year: 2005, song: "Let Me Love You", artist: "Mario" },
  { year: 2005, song: "Hollaback Girl", artist: "Gwen Stefani" },
  { year: 2005, song: "We Belong Together", artist: "Mariah Carey" },
  { year: 2005, song: "Don't Cha", artist: "The Pussycat Dolls" },
  { year: 2005, song: "Gold Digger", artist: "Kanye West" },
  { year: 2005, song: "Run It!", artist: "Chris Brown" },
  { year: 2005, song: "Be Without You", artist: "Mary J. Blige" },
  { year: 2005, song: "Grillz", artist: "Nelly" },
  { year: 2006, song: "Bad Day", artist: "Daniel Powter" },
  { year: 2006, song: "Temperature", artist: "Sean Paul" },
  { year: 2006, song: "Promiscuous", artist: "Nelly Furtado" },
  { year: 2006, song: "London Bridge", artist: "Fergie" },
  { year: 2006, song: "SexyBack", artist: "Justin Timberlake" },
  { year: 2006, song: "My Love", artist: "Justin Timberlake" },
  { year: 2006, song: "Money Maker", artist: "Ludacris" },
  { year: 2006, song: "Smack That", artist: "Akon" },
  { year: 2007, song: "Irreplaceable", artist: "Beyonce" },
  { year: 2007, song: "This Is Why I'm Hot", artist: "Mims" },
  { year: 2007, song: "Glamorous", artist: "Fergie" },
  { year: 2007, song: "Umbrella", artist: "Rihanna" },
  { year: 2007, song: "Big Girls Don't Cry", artist: "Fergie" },
  { year: 2007, song: "The Way I Are", artist: "Timbaland" },
  { year: 2007, song: "Buy U a Drank", artist: "T-Pain" },
  { year: 2007, song: "Gimme More", artist: "Britney Spears" },
  { year: 2007, song: "No One", artist: "Alicia Keys" },
  { year: 2007, song: "Low", artist: "Flo Rida" },
  { year: 2008, song: "With You", artist: "Chris Brown" },
  { year: 2008, song: "Bleeding Love", artist: "Leona Lewis" },
  { year: 2008, song: "Love in This Club", artist: "Usher" },
  { year: 2008, song: "No Air", artist: "Jordin Sparks" },
  { year: 2008, song: "Lollipop", artist: "Lil Wayne" },
  { year: 2008, song: "Bleeding Love", artist: "Leona Lewis" },
  { year: 2008, song: "Take a Bow", artist: "Rihanna" },
  { year: 2008, song: "I Kissed a Girl", artist: "Katy Perry" },
  { year: 2008, song: "Disturbia", artist: "Rihanna" },
  { year: 2008, song: "So What", artist: "Pink" },
  { year: 2008, song: "Whatever You Like", artist: "T.I." },
  { year: 2008, song: "Live Your Life", artist: "T.I." },
  { year: 2009, song: "Right Round", artist: "Flo Rida" },
  { year: 2009, song: "Poker Face", artist: "Lady Gaga" },
  { year: 2009, song: "Single Ladies (Put a Ring on It)", artist: "Beyonce" },
  { year: 2009, song: "Boom Boom Pow", artist: "The Black Eyed Peas" },
  { year: 2009, song: "I Gotta Feeling", artist: "The Black Eyed Peas" },
  { year: 2009, song: "Down", artist: "Jay Sean" },
  { year: 2009, song: "Empire State of Mind", artist: "Jay-Z" },
  { year: 2009, song: "Whatcha Say", artist: "Jason Derulo" },
  { year: 2010, song: "Tik Tok", artist: "Kesha" },
  { year: 2010, song: "Bad Romance", artist: "Lady Gaga" },
  { year: 2010, song: "Break Your Heart", artist: "Taio Cruz" },
  { year: 2010, song: "Nothin' on You", artist: "B.o.B" },
  { year: 2010, song: "OMG", artist: "Usher" },
  { year: 2010, song: "California Gurls", artist: "Katy Perry" },
  { year: 2010, song: "Teenage Dream", artist: "Katy Perry" },
  { year: 2010, song: "Like a G6", artist: "Far East Movement" },
  { year: 2010, song: "Just the Way You Are", artist: "Bruno Mars" },
  { year: 2010, song: "We R Who We R", artist: "Kesha" },
  { year: 2010, song: "Firework", artist: "Katy Perry" },
  { year: 2011, song: "Grenade", artist: "Bruno Mars" },
  { year: 2011, song: "Hold It Against Me", artist: "Britney Spears" },
  { year: 2011, song: "Born This Way", artist: "Lady Gaga" },
  { year: 2011, song: "S&M", artist: "Rihanna" },
  { year: 2011, song: "E.T.", artist: "Katy Perry" },
  { year: 2011, song: "Party Rock Anthem", artist: "LMFAO" },
  { year: 2011, song: "Give Me Everything", artist: "Pitbull" },
  { year: 2011, song: "Moves Like Jagger", artist: "Maroon 5" },
  { year: 2011, song: "Sexy and I Know It", artist: "LMFAO" },
  { year: 2011, song: "We Found Love", artist: "Rihanna" },
  { year: 2012, song: "Somebody That I Used to Know", artist: "Gotye" },
  { year: 2012, song: "Part of Me", artist: "Katy Perry" },
  { year: 2012, song: "Whistle", artist: "Flo Rida" },
  { year: 2012, song: "Payphone", artist: "Maroon 5" },
  { year: 2012, song: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { year: 2012, song: "Wide Awake", artist: "Katy Perry" },
  { year: 2012, song: "One More Night", artist: "Maroon 5" },
  { year: 2012, song: "Some Nights", artist: "fun." },
  { year: 2012, song: "Diamonds", artist: "Rihanna" },
  { year: 2013, song: "Thrift Shop", artist: "Macklemore & Ryan Lewis" },
  { year: 2013, song: "Harlem Shake", artist: "Baauer" },
  { year: 2013, song: "Same Love", artist: "Macklemore & Ryan Lewis" },
  { year: 2013, song: "Blurred Lines", artist: "Robin Thicke" },
  { year: 2013, song: "Radioactive", artist: "Imagine Dragons" },
  { year: 2013, song: "Roar", artist: "Katy Perry" },
  { year: 2013, song: "Wrecking Ball", artist: "Miley Cyrus" },
  { year: 2013, song: "The Monster", artist: "Eminem" },
  { year: 2013, song: "Royals", artist: "Lorde" },
  { year: 2014, song: "Dark Horse", artist: "Katy Perry" },
  { year: 2014, song: "Happy", artist: "Pharrell Williams" },
  { year: 2014, song: "All of Me", artist: "John Legend" },
  { year: 2014, song: "Fancy", artist: "Iggy Azalea" },
  { year: 2014, song: "Problem", artist: "Ariana Grande" },
  { year: 2014, song: "Anaconda", artist: "Nicki Minaj" },
  { year: 2014, song: "All About That Bass", artist: "Meghan Trainor" },
  { year: 2014, song: "Bang Bang", artist: "Jessie J" },
  { year: 2014, song: "Blank Space", artist: "Taylor Swift" },
  { year: 2015, song: "Uptown Funk", artist: "Mark Ronson" },
  { year: 2015, song: "Trap Queen", artist: "Fetty Wap" },
  { year: 2015, song: "See You Again", artist: "Wiz Khalifa" },
  { year: 2015, song: "Bad Blood", artist: "Taylor Swift" },
  { year: 2015, song: "Cheerleader", artist: "OMI" },
  { year: 2015, song: "Watch Me", artist: "Silento" },
  { year: 2015, song: "The Hills", artist: "The Weeknd" },
  { year: 2015, song: "Sorry", artist: "Justin Bieber" },
  { year: 2015, song: "What Do You Mean?", artist: "Justin Bieber" },
  { year: 2015, song: "Hotline Bling", artist: "Drake" },
  { year: 2015, song: "Hello", artist: "Adele" },
  { year: 2016, song: "Work", artist: "Rihanna" },
  { year: 2016, song: "Love Yourself", artist: "Justin Bieber" },
  { year: 2016, song: "Panda", artist: "Desiigner" },
  { year: 2016, song: "One Dance", artist: "Drake" },
  { year: 2016, song: "Cheap Thrills", artist: "Sia" },
  { year: 2016, song: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
  { year: 2016, song: "Closer", artist: "The Chainsmokers" },
  { year: 2016, song: "Starboy", artist: "The Weeknd" },
  { year: 2017, song: "Black Beatles", artist: "Rae Sremmurd" },
  { year: 2017, song: "Bad and Boujee", artist: "Migos" },
  { year: 2017, song: "Shape of You", artist: "Ed Sheeran" },
  { year: 2017, song: "Humble", artist: "Kendrick Lamar" },
  { year: 2017, song: "Despacito", artist: "Luis Fonsi" },
  { year: 2017, song: "Look What You Made Me Do", artist: "Taylor Swift" },
  { year: 2017, song: "Rockstar", artist: "Post Malone" },
  { year: 2018, song: "Perfect", artist: "Ed Sheeran" },
  { year: 2018, song: "God's Plan", artist: "Drake" },
  { year: 2018, song: "Meant to Be", artist: "Bebe Rexha" },
  { year: 2018, song: "Nice for What", artist: "Drake" },
  { year: 2018, song: "This Is America", artist: "Childish Gambino" },
  { year: 2018, song: "I Like It", artist: "Cardi B" },
  { year: 2018, song: "In My Feelings", artist: "Drake" },
  { year: 2018, song: "Sicko Mode", artist: "Travis Scott" },
  { year: 2019, song: "Sunflower", artist: "Post Malone" },
  { year: 2019, song: "Without Me", artist: "Halsey" },
  { year: 2019, song: "7 Rings", artist: "Ariana Grande" },
  { year: 2019, song: "Old Town Road", artist: "Lil Nas X" },
  { year: 2019, song: "Bad Guy", artist: "Billie Eilish" },
  { year: 2019, song: "Senorita", artist: "Shawn Mendes" },
  { year: 2019, song: "Truth Hurts", artist: "Lizzo" },
  { year: 2020, song: "The Box", artist: "Roddy Ricch" },
  { year: 2020, song: "Circles", artist: "Post Malone" },
  { year: 2020, song: "Don't Start Now", artist: "Dua Lipa" },
  { year: 2020, song: "Blinding Lights", artist: "The Weeknd" },
  { year: 2020, song: "Toosie Slide", artist: "Drake" },
  { year: 2020, song: "Rockstar", artist: "DaBaby" },
  { year: 2020, song: "Say So", artist: "Doja Cat" },
  { year: 2020, song: "Watermelon Sugar", artist: "Harry Styles" },
  { year: 2020, song: "Mood", artist: "24kGoldn" },
  { year: 2020, song: "Positions", artist: "Ariana Grande" },
  { year: 2021, song: "Drivers License", artist: "Olivia Rodrigo" },
  { year: 2021, song: "Up", artist: "Cardi B" },
  { year: 2021, song: "Leave the Door Open", artist: "Silk Sonic" },
  { year: 2021, song: "Peaches", artist: "Justin Bieber" },
  { year: 2021, song: "Good 4 U", artist: "Olivia Rodrigo" },
  { year: 2021, song: "Kiss Me More", artist: "Doja Cat" },
  { year: 2021, song: "Butter", artist: "BTS" },
  { year: 2021, song: "Industry Baby", artist: "Lil Nas X" },
  { year: 2021, song: "Stay", artist: "The Kid Laroi" },
  { year: 2021, song: "Easy on Me", artist: "Adele" },
  { year: 2021, song: "All Too Well", artist: "Taylor Swift" },
  { year: 2022, song: "Heat Waves", artist: "Glass Animals" },
  { year: 2022, song: "Easy on Me", artist: "Adele" },
  { year: 2022, song: "As It Was", artist: "Harry Styles" },
  { year: 2022, song: "First Class", artist: "Jack Harlow" },
  { year: 2022, song: "About Damn Time", artist: "Lizzo" },
  { year: 2022, song: "Anti-Hero", artist: "Taylor Swift" },
  { year: 2022, song: "Unholy", artist: "Sam Smith" },
  { year: 2023, song: "Kill Bill", artist: "SZA" },
  { year: 2023, song: "Flowers", artist: "Miley Cyrus" },
  { year: 2023, song: "Last Night", artist: "Morgan Wallen" },
  { year: 2023, song: "Fast Car", artist: "Luke Combs" },
  { year: 2023, song: "Cruel Summer", artist: "Taylor Swift" },
  { year: 2023, song: "Paint the Town Red", artist: "Doja Cat" },
  { year: 2023, song: "Lovin on Me", artist: "Jack Harlow" },
  { year: 2024, song: "Lose Control", artist: "Teddy Swims" },
  { year: 2024, song: "Texas Hold 'Em", artist: "Beyonce" },
  { year: 2024, song: "Beautiful Things", artist: "Benson Boone" },
  { year: 2024, song: "I Had Some Help", artist: "Post Malone" },
  { year: 2024, song: "Espresso", artist: "Sabrina Carpenter" },
  { year: 2024, song: "Please Please Please", artist: "Sabrina Carpenter" },
  { year: 2024, song: "Birds of a Feather", artist: "Billie Eilish" },
  { year: 2024, song: "Die with a Smile", artist: "Lady Gaga and Bruno Mars" },
  { year: 2025, song: "Luther", artist: "Kendrick Lamar" },
  { year: 2025, song: "Ordinary", artist: "Alex Warren" },
];
